# Generated by Django 5.2.8 on 2025-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
